actor.o: actor.c config.h actor.h sysdep.h error.h
dungeon.o: dungeon.c main.h config.h dungeon.h sysdep.h error.h \
 game.h misc.h monster.h player.h sprite.h map.h draw_map.h
error.o: error.c error.h
game.o: game.c main.h config.h dungeon.h sysdep.h error.h game.h \
 misc.h monster.h player.h
misc.o: misc.c main.h config.h dungeon.h sysdep.h error.h game.h \
 misc.h monster.h player.h
monster.o: monster.c main.h config.h dungeon.h sysdep.h error.h \
 game.h misc.h monster.h player.h
player.o: player.c main.h config.h dungeon.h sysdep.h error.h game.h \
 misc.h monster.h player.h
qdragon.o: qdragon.c main.h config.h dungeon.h sysdep.h error.h game.h \
 misc.h monster.h player.h
sysdep.o: sysdep.c main.h config.h dungeon.h sysdep.h error.h game.h \
 misc.h monster.h player.h
