dungeon.o: dungeon.c qdragon.h config.h dungeon.h sysdep.h error.h \
 game.h misc.h monster.h player.h sprite.h map.h draw_map.h
error.o: error.c error.h
game.o: game.c qdragon.h config.h dungeon.h sysdep.h error.h game.h \
 misc.h monster.h player.h
misc.o: misc.c qdragon.h config.h dungeon.h sysdep.h error.h game.h \
 misc.h monster.h player.h
monster.o: monster.c qdragon.h config.h dungeon.h sysdep.h error.h \
 game.h misc.h monster.h player.h
player.o: player.c qdragon.h config.h dungeon.h sysdep.h error.h game.h \
 misc.h monster.h player.h
qdragon.o: qdragon.c qdragon.h config.h dungeon.h sysdep.h error.h game.h \
 misc.h monster.h player.h
sysdep.o: sysdep.c qdragon.h config.h dungeon.h sysdep.h error.h game.h \
 misc.h monster.h player.h
